#spring.cloud.config.enabled=false

limits-service.minimum= 1
limits-service.maximum= 998

spring.application.name=limits-service
spring.config.import=optional:configserver:http://localhost:8890/

spring.profiles.active=dev 
#Now by default it's picking dev profile
#spring.cloud.config.profile=qa 
#Active profile is dev but in below line, it qa so it's picking qa

#spring.cloud.config.server.git.uri=file:///C:/My Folder/Eclipse/Microservices