spring.application.name=api-gateway

server.port=8765
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#http://localhost:8765/CURRENCY-CONVERSION/currency-conversion/from/USD/to/INR/quantity/10
#http://localhost:8765/currency-conversion/currency-conversion/from/USD/to/INR/quantity/10
#the above property lower case it's change the "CURRENCY-CONVERSION -- currency-conversion" 
