spring.application.name=spring-cloud-config-server

server.port=8890

spring.cloud.config.server.git.uri=file:///My Folder/Eclipse/Microservice-config-server
#C:\My Folder\Eclipse\Microservice-config-server
spring.cloud.config.server.bootstrap=true