spring.application.name=naming-server
server.port=8761

eureka.client.register-with-eureka=false 
#not launching eureka serve
eureka.client.fetch-registry=false

#spring.config.import=optional:configserver:
