server:
  port: 8888
#For git url local or git-hub
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Sumit(lecture Notes)/Microservices-june/Local-repo/
#to set-up with eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
