spring.application.name=currency-conversion
server.port=8100


#URL http://localhost:8100/currency-conversion/from/USD/to/INR/quantity/10

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka



#Docker --zipkin
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]